// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/dps-wmhris/backend/internal/di"
	http6 "github.com/dps-wmhris/backend/internal/modules/analytics/adapter/inbound/http"
	mysql6 "github.com/dps-wmhris/backend/internal/modules/analytics/adapter/outbound/mysql"
	usecase6 "github.com/dps-wmhris/backend/internal/modules/analytics/application/usecase"
	http5 "github.com/dps-wmhris/backend/internal/modules/catalog/adapter/inbound/http"
	mysql5 "github.com/dps-wmhris/backend/internal/modules/catalog/adapter/outbound/mysql"
	usecase5 "github.com/dps-wmhris/backend/internal/modules/catalog/application/usecase"
	http7 "github.com/dps-wmhris/backend/internal/modules/hris/adapter/inbound/http"
	mysql7 "github.com/dps-wmhris/backend/internal/modules/hris/adapter/outbound/mysql"
	usecase7 "github.com/dps-wmhris/backend/internal/modules/hris/application/usecase"
	http2 "github.com/dps-wmhris/backend/internal/modules/iam/adapter/inbound/http"
	mysql2 "github.com/dps-wmhris/backend/internal/modules/iam/adapter/outbound/mysql"
	usecase2 "github.com/dps-wmhris/backend/internal/modules/iam/application/usecase"
	http3 "github.com/dps-wmhris/backend/internal/modules/inventory/adapter/inbound/http"
	mysql3 "github.com/dps-wmhris/backend/internal/modules/inventory/adapter/outbound/mysql"
	usecase3 "github.com/dps-wmhris/backend/internal/modules/inventory/application/usecase"
	http4 "github.com/dps-wmhris/backend/internal/modules/misc/adapter/inbound/http"
	mysql4 "github.com/dps-wmhris/backend/internal/modules/misc/adapter/outbound/mysql"
	usecase4 "github.com/dps-wmhris/backend/internal/modules/misc/application/usecase"
	"github.com/dps-wmhris/backend/internal/modules/system/adapter/inbound/event"
	"github.com/dps-wmhris/backend/internal/modules/system/adapter/inbound/http"
	"github.com/dps-wmhris/backend/internal/modules/system/adapter/outbound/mysql"
	"github.com/dps-wmhris/backend/internal/modules/system/application/usecase"
	"github.com/dps-wmhris/backend/internal/shared/database"
	"github.com/jmoiron/sqlx"
)

// Injectors from wire.go:

func InitializeAPI(db *sqlx.DB) (*di.Container, error) {
	systemLogRepository := mysql.NewSystemLogRepository(db)
	systemLogService := usecase.NewSystemLogService(systemLogRepository)
	systemLogHandler := http.NewSystemLogHandler(systemLogService)
	transactionManager := database.NewTransactionManager(db)
	roleRepository := mysql2.NewRoleRepository(db)
	eventBus, err := di.ProvideEventBus()
	if err != nil {
		return nil, err
	}
	roleUseCase := usecase2.NewRoleUseCase(transactionManager, roleRepository, eventBus)
	roleHandler := http2.NewRoleHandler(roleUseCase)
	userRepository := mysql2.NewUserRepository(db)
	userUseCase := usecase2.NewUserUseCase(transactionManager, userRepository, eventBus)
	userHandler := http2.NewUserHandler(userUseCase)
	adminUserRepository := mysql2.NewAdminUserRepository(db)
	adminUserUseCase := usecase2.NewAdminUserUseCase(transactionManager, adminUserRepository, roleRepository, eventBus)
	adminUserHandler := http2.NewAdminUserHandler(adminUserUseCase)
	salesChannelRepository := mysql3.NewSalesChannelRepository(db)
	salesChannelService := usecase3.NewSalesChannelService(transactionManager, salesChannelRepository, eventBus)
	salesChannelHandler := http3.NewSalesChannelHandler(salesChannelService)
	paperSizeRepository := mysql4.NewPaperSizeRepository(db)
	paperSizeService := usecase4.NewPaperSizeService(transactionManager, paperSizeRepository, eventBus)
	paperSizeHandler := http4.NewPaperSizeHandler(paperSizeService)
	stickerTemplateRepository := mysql4.NewStickerTemplateRepository(db)
	stickerTemplateService := usecase4.NewStickerTemplateService(transactionManager, stickerTemplateRepository, eventBus)
	stickerTemplateHandler := http4.NewStickerTemplateHandler(stickerTemplateService)
	notificationRepository := mysql.NewNotificationRepository(db)
	firebaseSignalService := usecase.NewFirebaseSignalService()
	notificationService := usecase.NewNotificationService(transactionManager, notificationRepository, firebaseSignalService)
	notificationHandler := http.NewNotificationHandler(notificationService)
	jobRepository := mysql.NewJobRepository(db)
	jobService := usecase.NewJobService(jobRepository)
	jobHandler := http.NewJobHandler(jobService)
	storageService := usecase.NewStorageService()
	uploadHandler := http.NewUploadHandler(storageService)
	mediaRepository := mysql.NewMediaRepository(db)
	productRepository := mysql5.NewProductRepository(db)
	mediaService := usecase.NewMediaService(transactionManager, mediaRepository, productRepository, storageService)
	mediaHandler := http.NewMediaHandler(mediaService, storageService, jobService)
	categoryRepository := mysql5.NewCategoryRepository(db)
	categoryUseCase := usecase5.NewCategoryUseCase(categoryRepository)
	categoryHandler := http5.NewCategoryHandler(categoryUseCase)
	logListener := event.NewLogListener(systemLogService)
	productAuditRepository := mysql5.NewProductAuditRepository(db)
	productUseCase := usecase5.NewProductUseCase(transactionManager, productRepository, productAuditRepository, categoryRepository)
	productHandler := http5.NewProductHandler(productUseCase, jobService)
	locationRepository := mysql3.NewLocationRepository(db)
	locationUseCase := usecase3.NewLocationUseCase(transactionManager, locationRepository, eventBus)
	locationHandler := http3.NewLocationHandler(locationUseCase)
	stockRepository := mysql3.NewStockRepository(db)
	pickingRepository := mysql3.NewPickingRepository(db)
	stockUseCase := usecase3.NewStockUseCase(transactionManager, stockRepository, productRepository, locationRepository, userRepository, pickingRepository)
	stockHandler := http3.NewStockHandler(stockUseCase, jobService)
	stockRequestRepository := mysql3.NewStockRequestRepository(db)
	stockRequestUseCase := usecase3.NewStockRequestUseCase(transactionManager, stockRequestRepository, stockUseCase, notificationService)
	stockRequestHandler := http3.NewStockRequestHandler(stockRequestUseCase)
	packageHandler := http5.NewPackageHandler(jobService)
	returnRepository := mysql3.NewReturnRepository(db)
	returnUseCase := usecase3.NewReturnUseCase(transactionManager, returnRepository, locationRepository, stockRepository)
	returnHandler := http3.NewReturnHandler(returnUseCase)
	investigationRepository := mysql3.NewInvestigationRepository(db)
	investigationUseCase := usecase3.NewInvestigationUseCase(transactionManager, investigationRepository, locationRepository, stockRepository)
	investigationHandler := http3.NewInvestigationHandler(investigationUseCase)
	statsRepository := mysql6.NewStatsRepository(db)
	statsService := usecase6.NewStatsService(statsRepository)
	statsHandler := http6.NewStatsHandler(statsService)
	reportRepository := mysql6.NewReportRepository(db)
	reportService := usecase6.NewReportService(reportRepository)
	reportHandler := http6.NewReportHandler(reportService, jobService, storageService, jobRepository)
	statisticRepository := mysql6.NewStatisticRepository(db)
	statisticService := usecase6.NewStatisticService(statisticRepository, jobRepository)
	statisticHandler := http6.NewStatisticHandler(statisticService)
	shiftRepository := mysql7.NewShiftRepository(db)
	shiftUseCase := usecase7.NewShiftUseCase(transactionManager, shiftRepository)
	shiftHandler := http7.NewShiftHandler(shiftUseCase)
	pickingUseCase := usecase3.NewPickingUseCase(transactionManager, pickingRepository, locationRepository, stockRepository, jobService, productRepository)
	pickingHandler := http3.NewPickingHandler(jobService, pickingUseCase)
	scheduleRepository := mysql7.NewScheduleRepository(db)
	scheduleUseCase := usecase7.NewScheduleUseCase(scheduleRepository, shiftRepository, userRepository)
	scheduleHandler := http7.NewScheduleHandler(scheduleUseCase, jobService)
	attendanceRepository := mysql7.NewAttendanceRepository(db)
	settingRepository := mysql.NewSettingRepository(db)
	attendanceUseCase := usecase7.NewAttendanceUseCase(attendanceRepository, userRepository, shiftRepository, scheduleRepository, settingRepository)
	attendanceHandler := http7.NewAttendanceHandler(attendanceUseCase, jobService)
	container := di.NewContainer(systemLogHandler, roleHandler, userHandler, adminUserHandler, salesChannelHandler, paperSizeHandler, stickerTemplateHandler, notificationHandler, jobHandler, uploadHandler, mediaHandler, categoryHandler, eventBus, logListener, productHandler, locationHandler, stockHandler, stockRequestHandler, packageHandler, returnHandler, investigationHandler, statsHandler, reportHandler, statisticHandler, shiftHandler, pickingHandler, scheduleHandler, attendanceHandler)
	return container, nil
}
