// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/dps-wmhris/backend/internal/di"
	mysql2 "github.com/dps-wmhris/backend/internal/modules/analytics/adapter/outbound/mysql"
	usecase2 "github.com/dps-wmhris/backend/internal/modules/analytics/application/usecase"
	mysql4 "github.com/dps-wmhris/backend/internal/modules/catalog/adapter/outbound/mysql"
	usecase5 "github.com/dps-wmhris/backend/internal/modules/catalog/application/usecase"
	mysql5 "github.com/dps-wmhris/backend/internal/modules/hris/adapter/outbound/mysql"
	usecase3 "github.com/dps-wmhris/backend/internal/modules/hris/application/usecase"
	mysql6 "github.com/dps-wmhris/backend/internal/modules/iam/adapter/outbound/mysql"
	"github.com/dps-wmhris/backend/internal/modules/inventory/adapter/outbound/erp"
	mysql3 "github.com/dps-wmhris/backend/internal/modules/inventory/adapter/outbound/mysql"
	usecase4 "github.com/dps-wmhris/backend/internal/modules/inventory/application/usecase"
	"github.com/dps-wmhris/backend/internal/modules/system/adapter/outbound/mysql"
	"github.com/dps-wmhris/backend/internal/modules/system/application/usecase"
	"github.com/dps-wmhris/backend/internal/shared/database"
	"github.com/jmoiron/sqlx"
)

// Injectors from wire.go:

func InitializeWorker(db *sqlx.DB) (*di.WorkerContainer, error) {
	jobRepository := mysql.NewJobRepository(db)
	jobService := usecase.NewJobService(jobRepository)
	statisticRepository := mysql2.NewStatisticRepository(db)
	statisticService := usecase2.NewStatisticService(statisticRepository, jobRepository)
	storageService := usecase.NewStorageService()
	stockRepository := mysql3.NewStockRepository(db)
	reportRepository := mysql2.NewReportRepository(db)
	productRepository := mysql4.NewProductRepository(db)
	categoryRepository := mysql4.NewCategoryRepository(db)
	exportService := usecase2.NewExportService(jobRepository, statisticService, storageService, stockRepository, reportRepository, productRepository, categoryRepository)
	firebaseSignalService := usecase.NewFirebaseSignalService()
	eventBus, err := di.ProvideEventBus()
	if err != nil {
		return nil, err
	}
	transactionManager := database.NewTransactionManager(db)
	mediaRepository := mysql.NewMediaRepository(db)
	mediaService := usecase.NewMediaService(transactionManager, mediaRepository, productRepository, storageService)
	attendanceRepository := mysql5.NewAttendanceRepository(db)
	userRepository := mysql6.NewUserRepository(db)
	shiftRepository := mysql5.NewShiftRepository(db)
	scheduleRepository := mysql5.NewScheduleRepository(db)
	settingRepository := mysql.NewSettingRepository(db)
	attendanceUseCase := usecase3.NewAttendanceUseCase(attendanceRepository, userRepository, shiftRepository, scheduleRepository, settingRepository)
	scheduleUseCase := usecase3.NewScheduleUseCase(scheduleRepository, shiftRepository, userRepository)
	fulfilmentRepository := mysql3.NewFulfilmentRepository(db)
	locationRepository := mysql3.NewLocationRepository(db)
	keljaERPClient := erp.NewKeljaClient()
	fulfilmentUseCase := usecase4.NewFulfilmentUseCase(transactionManager, fulfilmentRepository, locationRepository, stockRepository, jobService, productRepository, keljaERPClient, eventBus)
	stockUseCase := usecase4.NewStockUseCase(transactionManager, stockRepository, productRepository, locationRepository, userRepository, fulfilmentRepository, eventBus)
	productAuditRepository := mysql4.NewProductAuditRepository(db)
	productUseCase := usecase5.NewProductUseCase(transactionManager, productRepository, productAuditRepository, categoryRepository)
	stockTransactionRepository := mysql3.NewStockTransactionRepository(db)
	stockTransactionUseCase := usecase4.NewStockTransactionService(transactionManager, stockTransactionRepository, locationRepository, eventBus)
	workerContainer := di.NewWorkerContainer(jobService, statisticService, storageService, exportService, firebaseSignalService, eventBus, mediaService, attendanceUseCase, scheduleUseCase, fulfilmentUseCase, stockUseCase, productUseCase, stockTransactionUseCase, keljaERPClient)
	return workerContainer, nil
}
