// src/plugins/fontawesome.js
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faHome,
  faUser,
  faCog,
  faSignOutAlt,
  faCalendarAlt,
  faArrowLeft,
  faBoxArchive,
  faWarehouse,
  faListUl,
  faFolderTree,
  faServer,
  faUsers,
  faCalendar,
  faUpload,
  faSort,
  faSortUp,
  faSortDown,
  faFilter,
  faFilterCircleXmark,
  faPlus,
  faChartLine,
  faChevronDown,
  faUserCircle,
  faUserCog,
  faLanguage,
  faCheckCircle,
  faExclamationTriangle,
  faInfoCircle,
  faSpinner,
  faUserLock,
  faFileImport,
  faSearch,
  faRightLeft,
  faPencil,
  faHistory,
  faCloudArrowUp,
} from '@fortawesome/free-solid-svg-icons'

library.add(
  faHome,
  faUser,
  faCog,
  faSignOutAlt,
  faCalendarAlt,
  faArrowLeft,
  faBoxArchive,
  faWarehouse,
  faListUl,
  faFolderTree,
  faServer,
  faUsers,
  faCalendar,
  faUpload,
  faSort,
  faSortUp,
  faSortDown,
  faFilter,
  faFilterCircleXmark,
  faPlus,
  faChartLine,
  faChevronDown,
  faUserCircle,
  faUserCog,
  faLanguage,
  faCheckCircle,
  faExclamationTriangle,
  faInfoCircle,
  faSpinner,
  faUserLock,
  faFileImport,
  faSearch,
  faRightLeft,
  faPencil,
  faHistory,
  faCloudArrowUp,
)

export default FontAwesomeIcon
